spring.application.name=Complaint-Tracking-System

server.port=1503

spring.datasoucre.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/complainttracking
spring.datasource.username=root
spring.datasource.password=root@1503

spring.jpa.hibernate.ddl-auto=update
srping.jpa.show-sql=true
